# Generated by Django 5.2.8 on 2026-06-17 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='avatars/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='voice_sample',
            field=models.FileField(default=django.utils.timezone.now, upload_to='voice_samples/'),
            preserve_default=False,
        ),
    ]
