# Generated by Django 5.2.8 on 2026-06-17 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_generatedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedvideo',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.avatar'),
        ),
    ]
