# Generated by Django 5.2.8 on 2026-06-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_generatedvideo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='is_cartoon',
            field=models.BooleanField(default=False),
        ),
    ]
