# Generated by Django 5.2.8 on 2026-06-18 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_avatar_is_cartoon'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='heygen_avatar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
