# Generated by Django 5.2.8 on 2026-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_avatar_heygen_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='heygen_image_urls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='heygen_preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
